"""Templates package initialization."""

from langgraph_system_generator.templates.langgraph_templates import (
    BASIC_AGENT_TEMPLATE,
    SEQUENTIAL_WORKFLOW_TEMPLATE,
    PARALLEL_WORKFLOW_TEMPLATE,
    CONDITIONAL_WORKFLOW_TEMPLATE,
    STATE_TEMPLATE,
    IMPORTS_TEMPLATE
)

from langgraph_system_generator.templates.notebook_templates import (
    NOTEBOOK_HEADER_TEMPLATE,
    INSTALLATION_TEMPLATE,
    INSTALLATION_CODE,
    USAGE_TEMPLATE,
    USAGE_CODE_TEMPLATE,
    SECTION_HEADERS
)

__all__ = [
    "BASIC_AGENT_TEMPLATE",
    "SEQUENTIAL_WORKFLOW_TEMPLATE",
    "PARALLEL_WORKFLOW_TEMPLATE",
    "CONDITIONAL_WORKFLOW_TEMPLATE",
    "STATE_TEMPLATE",
    "IMPORTS_TEMPLATE",
    "NOTEBOOK_HEADER_TEMPLATE",
    "INSTALLATION_TEMPLATE",
    "INSTALLATION_CODE",
    "USAGE_TEMPLATE",
    "USAGE_CODE_TEMPLATE",
    "SECTION_HEADERS"
]
